# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run:
          command: |
              git clone --branch ${CIRCLE_BRANCH} git@github.com:inform-health-informatics/Inform-DB.git || git clone --branch develop git@github.com:inform-health-informatics/Inform-DB.git
              cd Inform-DB
              mvn install -Dmaven.test.skip=true
              git clone --branch v1 git@github.com:inform-health-informatics/Inform-DB.git Inform-DB1
              cd Inform-DB1
              mvn install -Dmaven.test.skip=true
              git clone --branch ${CIRCLE_BRANCH} git@github.com:inform-health-informatics/Emap-Interchange.git || git clone --branch develop git@github.com:inform-health-informatics/Emap-Interchange.git

              cd Emap-Interchange
              # run tests so that test classes can be used in current testing
              mvn install
      - run:
          command: |
             mvn dependency:go-offline

      - run:
          command: |
             TZ="Europe/London" mvn -Dspring.profiles.active=test integration-test -Dstart-class=uk.ac.ucl.rits.inform.datasinks.emapstar.App
             TZ="America/Chicago" mvn -Dspring.profiles.active=test integration-test -Dstart-class=uk.ac.ucl.rits.inform.datasinks.emapstar.App
