name: Develop test

on:
  push:
    branches: ["develop"]
  schedule:
    - cron:  '0 0 * * *'    # At midnight every day

jobs:
  set_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        run: |
          exit_code=$(curl -X GET -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" https://api.github.com/repos/inform-health-informatics/Emap-Core/git/matching-refs/tags/requires_test | grep -q requires_test; echo $?)
          if [ "$exit_code" == "0" ]; then
              tag_exists=true
          fi
          echo "tag_exists=$tag_exists" >> $GITHUB_ENV

  run_tests:
      uses: inform-health-informatics/Emap-Core/.github/workflows/test.yaml@develop
      needs: set-tag
      if: ${{ jobs.set_tag.env.tag_exists }}

  remove_tag:
    runs-on: ubuntu-latest
    needs: set-tag
    if: always()  # Won't delete a non-existing tag
    steps:
      - name: Delete tag
        run: |
          curl -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
          https://api.github.com/repos/inform-health-informatics/Emap-Core/git/refs/tags/requires_test
