name: Develop scheduled test

on:
  push:
    branches: ["develop"]
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_scheduled_test_if_tagged:
    uses: inform-health-informatics/emap-actions/.github/workflows/test_if_tagged.yaml@main
    with:
      repo: "Inform-DB"
    secrets:
      token: ${{ secrets.GH_ACCESS_TOKEN }}
