services:
  streamlit:
    build:
      context: ..
      dockerfile: monitoring/streamlit/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    env_file:
      - ../../config/streamlit-config-envs
    logging:
      driver: "json-file"
    restart: "no"
