services:
  fakeuds:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: fakeuds
      # should be from global config?
      POSTGRES_USER: inform_user
      POSTGRES_PASSWORD: inform
    volumes:
      - postgres-data-fakeuds:/var/lib/postgresql/data
      - ./init/uds:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "${FAKEUDS_PORT}:5432"
    profiles:
      - fakeuds-pg
  fakeuds-mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU17-ubuntu-22.04
    env_file:
      - ../../config/fakeuds-mssql-config-envs
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      TZ: "Europe/London"
    volumes:
      - mssql-data-fakeuds:/var/opt/mssql
    restart: unless-stopped
    ports:
      - "${FAKEUDS_MSSQL_PORT}:1433"
    profiles:
      - fakeuds-mssql


volumes:
  postgres-data-fakeuds:
  mssql-data-fakeuds:
