services:
  fakeuds:
    image: postgres:11-alpine
    env_file:
      - ../../config/fakeuds-postgres-config-envs
    volumes:
      - postgres-data-fakeuds:/var/lib/postgresql/data
      - ./init/uds:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "${FAKEUDS_PORT}:5432"

volumes:
  postgres-data-fakeuds:
