# This is an example of the global-configuration.yaml file
# that needs to be created in the emap-setup directory

###############################################################################

## Please edit sections with information for your setup.

###############################################################################

---
config:

  # this is the main INFORM git-hub directory
  main_git_dir:
    https://github.com/inform-health-informatics

  # this is whatever name you have chosen for this installation
  #NOTE: this must be unique on the docker host
  emap_project_name:
    my_project_name

  # list of required repositories and the branch you require
  # the list below shows those needed for a standard installation
  # you may wish to add others e.g. DBFiller for synthetic data

  # To add a repository use the following syntax
  # name_of_dir - should match name_of_repo_on_github unless we need two branches of same
  #   branch:  name_of_branch_you_wish_to_use
  #   repo_name: name_of_repo_on_github (only needed if we have a second branch of a repo
  #               and the name_of_dir is different
  repositories:
    Emap-Core:
      branch:  develop
    caboodle-vitalsigns:
      branch:  develop
    OMOP-ETL:
      branch:  event_driven
    Emap-interchange:
      branch:  master
    InformDB:
      branch:  develop
    hl7-vitals:
      branch:  vitalsigns
      repo_name: Emap-Core

  # Configuration data for the rabbitmq instance used by Spring in the pipeline

  spring_rabbitmq:
    SPRING_RABBITMQ_HOST: rabbitmq
    SPRING_RABBITMQ_PORT: 5672
    SPRING_RABBITMQ_USERNAME: my_name
    SPRING_RABBITMQ_PASSWORD: my_pw
    
  # Configuration used by global configuration
  
  rabbitmq_global:
    RABBITMQ_PORT: 5678
    RABBITMQ_ADMIN_PORT: 5679
  
  # Configuration for the IDS
  ids:
    IDS_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/ids
    IDS_SCHEMA: schemaname
    IDS_USERNAME: someuserids
    IDS_PASSWORD: redactedids

  # These dates are used to set the start and end dates between which data should be collected
  dates:
    start: 2020-06-04T00:00:00.000Z
    end:

  informdb:
    global:
      INFORMDB_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/ids
    Emap-Core:
      INFORMDB_SCHEMA: inform_schema
      INFORMDB_USERNAME: someuser
      INFORMDB_PASSWORD: redacted
    OMOP-ETL:
      INFORMDB_SCHEMA: inform_schema
      INFORMDB_USERNAME: someuser_omop
      INFORMDB_PASSWORD: redacted_omop
      INFORMDB_DDL_AUTO: update
      INFORM_INIT_MODE: always
    hl7-vitals:
      INFORMDB_SCHEMA: inform_schema_for_branch
      INFORMDB_USERNAME: someuseraaa
      INFORMDB_PASSWORD: redactedaaa

# These are the configurations for the caboodle.

  caboodle:
    CABOODLE_JDBC_URL: jdbc:sqlserver://caboodle_db
    CABOODLE_USERNAME: cab_user
    CABOODLE_PASSWORD: cab_password

# These are the configurations for the uds.

  uds:
    UDS_JDBC_URL: jdbc:postgresql://uds_db:5432/uds
    UDS_SCHEMA: caboodle_extract
    UDS_USERNAME: caboodle_vitals
    UDS_PASSWORD: inform

# These are the configurations for the omop.

  omop:
    OPS_DROP_AND_CREATE_SCHEMA: false
    OPS_SCHEMA: ops_dev
