name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        if: github.event.action == 'Run develop test'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 11 # also enables caching
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # adopt has moved to Eclipse Temurin
          cache: 'maven'
      - name: Clean
        run: mvn clean
      - name: Build and test
        run: mvn test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
