version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run:
          command: |
              git clone --branch ${CIRCLE_BRANCH} git@github.com:inform-health-informatics/Emap-Interchange.git || git clone --branch develop git@github.com:inform-health-informatics/Emap-Interchange.git
              cd Emap-Interchange
              # run tests so that test classes can be used in current testing
              mvn install
      - run:
          command: |
             mvn dependency:go-offline
      - run:
          command: |
             TZ="Europe/London" mvn test
             TZ="America/Chicago" mvn test

workflows:
  build:
    jobs:
      - build:
          context:
            - dockerhub