# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  compile:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run:
          name: a merge PR
          command: |
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
              git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
              git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
            fi

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "HL7Processor/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: |
             cd HL7Processor
             mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "HL7Processor/pom.xml" }}
        
      # run tests!
      - run:
          command: |
             cd HL7Processor
             mvn integration-test   #mvn integration-test

  # Following the example given at 
  # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
  docs-build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build docs
          command: cd HL7Processor && mkdir docsbuild && mvn javadoc:javadoc
      - persist_to_workspace:
          root: HL7Processor/docsbuild
          paths: .

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: HL7Processor/docsbuild
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "m.gillman@ucl.ac.uk"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist HL7Processor/docsbuild --src '{*.html,*.css,*.txt,*.js,uk/*}'


workflows:
  version: 2
  build:
    jobs:
      - compile
      - docs-build
      - docs-deploy:
          requires:
            - compile
            - docs-build
          filters:
            branches:
              only: master

