name: pytest

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        auto-update-conda: true

    - name: Install
      run: |
        conda activate test
        conda install --file requirements.txt
        python -m pip install . --no-deps
    - name: Test
      run: |
        cd tests && py.test
