server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    # nginx is behind docker, so the browser is using a different port number which nginx doesn't know about.
    # Use relative redirects to avoid redirecting to port 80. (301s are used when trailing slashes are omitted)
    absolute_redirect off;
    auth_basic           "Administrator’s Area";
    auth_basic_user_file conf.d/htpasswd;

    # don't cache failed DNS indefinitely
    resolver 127.0.0.11 valid=10s;

    access_log  /var/log/nginx/host.access.log  main;

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location / {
        root   /usr/share/nginx/html;
        include conf.d/shared/shared_location_config.conf;
    }
    # Using intermediate variables for the proxy_pass directives forces
    # late resolution of the hostname, so the portal still comes up if
    # the upstream container(s) are down.

    location /glowroot/ {
        include conf.d/shared/shared_location_config.conf;
        set $glowroot_upstream http://glowroot-central:4000;
        proxy_pass   $glowroot_upstream/;
        sub_filter 'href="/' 'href="/glowroot/';
        sub_filter 'src="/' 'src="/glowroot/';
    }

    location /streamlit/ {
        include conf.d/shared/shared_location_config.conf;
        set $streamlit_upstream http://streamlit:8501;
        proxy_pass   $streamlit_upstream/streamlit/;
        proxy_buffering off;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location /local-grafana/ {
        include conf.d/shared/shared_location_config.conf;
        # emap-portal and waveform-controller's lgtm service must be
        # on the same docker network, which must be manually created.
        set $grafana_upstream http://lgtm:3000;
        proxy_pass   $grafana_upstream;
        proxy_buffering off;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
