name: POST develop test trigger

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Post event
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        run: |
          for repo in Emap-Core Inform-DB Emap-Interchange emap-hl7-processor
          do
            curl -X POST "https://api.github.com/repos/inform-health-informatics/$repo/dispatches" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.GH_ACCESS_TOKEN }} \
            --data '{"event_type": "Run develop test", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          done
