name: PR checklist comment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SAFEHR_READ_ONLY_WORKER_ID }}
          private-key: ${{ secrets.SAFEHR_READ_ONLY_WORKER_KEY }}
          repositories: internal_emap_documentation
      - name: Checkout documentation
        uses: actions/checkout@v4
        with:
          repository: SAFEHR-data/internal_emap_documentation
          token: ${{ steps.generate-token.outputs.token }}
          ref: main
      - id: get-pr-checklist
        name: Get PR checklist
        uses: chuhlomin/render-template@v1.2
        with:
          template: SOP/pr_checklist.md
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-pr-checklist.outputs.result }}
