name: Core Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 11 # also enables caching
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build emap-star
        run: mvn clean install -Dmaven.test.skip=true
        working-directory: emap-star
      - name: Build emap-interchange
        run: mvn clean install # run tests so that test classes can be used in current testing
        working-directory: emap-interchange
      - name: Build and test core
        run: mvn clean -Dspring.profiles.active=test integration-test -Dstart-class=uk.ac.ucl.rits.inform.datasinks.emapstar.App
        working-directory: core
        env:
          TZ: "America/Chicago"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
