name: emap tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  repository_dispatch:
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: read # needed by paths-filter
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.filter.outputs.all }}
      core: ${{ steps.filter.outputs.core }}
      hl7-reader: ${{ steps.filter.outputs.hl7-reader }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            all:
              # changes that should trigger a full rebuild regardless
              - '.github/**'
              - 'emap-star/**'
              - 'emap-interchange/**'
            core:
              - 'core/**'
            hl7-reader:
              - 'hl7-reader/**'
  emap-star-tests:
    needs: [setup]
    runs-on: ubuntu-latest
    if: needs.setup.outputs.all == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Ensure we use JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run emap-star tests
        working-directory: emap-star
        run: mvn clean test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
  emap-interchange-tests:
    needs: [setup]
    runs-on: ubuntu-latest
    if: needs.setup.outputs.all == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Ensure we use JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run emap-interchange tests
        working-directory: emap-interchange
        run: mvn clean test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
  hl7-reader-tests:
    needs: [setup]
    runs-on: ubuntu-latest
    if: needs.setup.outputs.hl7-reader == 'true' || needs.setup.outputs.all == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Ensure we use JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build emap-star
        working-directory: emap-star
        run: mvn clean install
      - name: Build emap-interchange
        working-directory: emap-interchange
        run: mvn clean install
      - name: Run hl7-reader tests
        working-directory: hl7-reader
        run: mvn clean test
        env:
          TZ: "America/Chicago"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
  core-tests:
    needs: [setup]
    runs-on: ubuntu-latest
    if: needs.setup.outputs.core == 'true' || needs.setup.outputs.all == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Ensure we use JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build emap-star
        working-directory: emap-star
        run: mvn clean install
      - name: Build emap-interchange
        working-directory: emap-interchange
        run: mvn clean install
      - name: Build and test core
        run: mvn clean -Dspring.profiles.active=test integration-test -Dstart-class=uk.ac.ucl.rits.inform.datasinks.emapstar.App
        working-directory: core
        env:
          TZ: "America/Chicago"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
