name: hl7-reader tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_call:

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 11 # also enables caching
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # adopt has moved to Eclipse Temurin
          cache: 'maven'
      - name: Build emap-interchange
        run: mvn clean install # run tests so that test classes can be used in current testing
        working-directory: emap-interchange
      - name: Test hl7-reader
        run: mvn clean test
        working-directory: hl7-reader
        env:
          TZ: "America/Chicago"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'